### ISSUE TITLE
EdgeHub won't start due to an API version error

### ISSUE THREAD

**Issue by Heke1** [toolboc/azure-iot-edge-device-container#9]
When trying to run stuff in the container, EdgeHub fails with the following error:

```
`Unhandled exception. System.AggregateException: One or more errors occurred. (Error calling CreateServerCertificateAsync: Invalid or missing API version)
 ---> Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadCommunicationException- Message:Error calling CreateServerCertificateAsync: Invalid or missing API version, StatusCode:400, at:   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.HandleException(Exception ex, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 109
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 77
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.CreateServerCertificateAsync(String hostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 35
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId, String edgeHubHostname, DateTime expiration) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.EdgeHubCertificates.LoadAsync(IConfigurationRoot configuration, ILogger logger) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs:line 54
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 54
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33`
```
It seems that iotedge version is really old
```
>iotedge version
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

```

Latest release is 1.0.10.3.

**Comment by toolboc** [comment]
@Heke1,

This can be alleviated by modifying the deployment configuration for your azure-iot-edge-device-container to reference an updated version of the edgeAgent / edgeHub:

![image](https://user-images.githubusercontent.com/2018336/109830896-894a6680-7c04-11eb-90e5-b33f7e576213.png)

![image](https://user-images.githubusercontent.com/2018336/109830772-6cae2e80-7c04-11eb-9c39-104963ee389c.png)

The edgeAgent that is supplied in the existing azure-iot-edge-device-container images is able to retrieve and update itself based on it's associated deployment configuration. As such, this is the preferred strategy for updating the edgeAgent / edgeHub when using these containers as it does not require that we update the azure-iot-edge-device-container project as newer versions are released.

**Comment by pazniak** [comment]
I would like to reopen this issue, because edgeAgent self-update is not always enough. Current starting from version 1.0.10-1 backward compatibility with the iotedged was broken. edgeHub can't start because of an API error. The way I see it, this project could benefit from ability to update the iotedged version to the latest stable. Alternatively, it can download it and install it in the entrypoint script.
